### ISSUE TITLE
Changing URL

### ISSUE THREAD

**Issue by ghost** [grantholle/laravel-elixir-browser-sync-simple#2]
Hi, This is working actually but i can't figure out how to configure this.
It opens http://localhost:3000
but i want to my custom domain like http://laravel.dev
is it possible or like the name says is it simple?

**Comment by grantholle** [comment]
Were you able to get it working?

**Comment by ghost** [comment]
Nope. But i tried other similar plugins and same issue. I am looking sync docs. I would appreciate the help.

**Comment by grantholle** [comment]
I think because you may not understand what it's doing.

You have a custom vhost entry, laravel.dev. What browsersync does is create a proxy for that url at localhost:3000. This way there's no manual injecting of the javascript code on your part, it does that for you.

If you really need to maintain the laravel.dev url, then you won't need this or any plugin. You just need to install browsersync globally, and run `$ browser-sync start`, which will give you a snippet to put in your html. You will also need to configure it for which files to watch, etc.

**Comment by ghost** [comment]
You are right probably. I am new to laravel. Couple of days yet. I will give it a go. Thanks.
