### ISSUE TITLE
view files not causing sync

### ISSUE THREAD

**Issue by andheiberg** [grantholle/laravel-elixir-browser-sync-simple#3]
I keep my resources in the standard 'resources/views' folder.

Changing view files does not cause a sync, but assets work.

Any clues as to why that might be?

**Comment by grantholle** [comment]
Should be good to go now with version 2.1! Good catch, thanks

**Comment by andheiberg** [comment]
Oh cool, assumed that syntax was correct haha was playing with the path.

Cheers! Great package only one that worked for me and it's the cleaner one

**Comment by andheiberg** [comment]
According to semantic versioning though you should have made that an 2.0. though?

**Comment by grantholle** [comment]
Yeah, maybe. Depends on how you interpret "MINOR version when you _add functionality_ in a backwards-compatible manner, and PATCH version when you make backwards-compatible _bug fixes_."

Technically both of those are correct. The added functionality was that it refreshes on a view file change, but it could also be considered a bug fix because it should have done that in the first place. Maybe I should have incremented both to 2.1.1. The world may never know. I'm content with a 2.1 because it doesn't get updated all that often anyway, but I appreciate your advice and the time you took to put in the functionality request/bug fix.

:two_men_holding_hands:

**Comment by andheiberg** [comment]
Oh haha wasn't meant as anything derogatory, just a thought that popped into my mind, sorry if I upset you.

Cheers, would have sent a pull, but didn't know the fix :) Thanks for fixing it so quickly.
